# Generated by Django 6.1.1 on 2026-10-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('date_of_birth', models.DateField()),
                ('onboarded_at', models.DateField()),
                ('kyc_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING', 'Pending'), ('REVIEW', 'Review')], max_length=10)),
                ('segment', models.CharField(choices=[('Mass', 'Mass'), ('Affluent', 'Affluent'), ('HNI', 'Hni')], max_length=10)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['city'], name='customer_city_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kyc_status__in', ['VERIFIED', 'PENDING', 'REVIEW'])), name='customer_kyc_status_valid'), models.CheckConstraint(condition=models.Q(('segment__in', ['Mass', 'Affluent', 'HNI'])), name='customer_segment_valid')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('BROKERAGE', 'Brokerage'), ('MUTUAL_FUND', 'Mutual Fund'), ('RETIREMENT', 'Retirement')], max_length=12)),
                ('provider', models.CharField(max_length=80)),
                ('opened_at', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('CLOSED', 'Closed')], max_length=8)),
                ('base_currency', models.CharField(max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='portfolio.customer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('RETIREMENT', 'Retirement'), ('EDUCATION', 'Education'), ('HOME_PURCHASE', 'Home Purchase'), ('EMERGENCY_FUND', 'Emergency Fund'), ('WEALTH_CREATION', 'Wealth Creation'), ('TRAVEL', 'Travel')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_funded_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('target_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='portfolio.customer')),
            ],
            options={
                'ordering': ['target_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Equity'), ('ETF', 'Etf'), ('MUTUAL_FUND', 'Mutual Fund'), ('BOND', 'Bond'), ('REIT', 'Reit'), ('GSEC', 'Gsec')], max_length=12)),
                ('sector', models.CharField(blank=True, default='', max_length=60)),
                ('exchange', models.CharField(choices=[('NSE', 'Nse'), ('BSE', 'Bse'), ('OTC', 'Otc')], max_length=3)),
                ('currency', models.CharField(max_length=3)),
                ('last_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price_as_of', models.DateField()),
                ('risk_band', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=6)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('asset_class__in', ['EQUITY', 'ETF', 'MUTUAL_FUND', 'BOND', 'REIT', 'GSEC'])), name='instrument_asset_class_valid'), models.CheckConstraint(condition=models.Q(('exchange__in', ['NSE', 'BSE', 'OTC'])), name='instrument_exchange_valid'), models.CheckConstraint(condition=models.Q(('risk_band__in', ['LOW', 'MEDIUM', 'HIGH'])), name='instrument_risk_band_valid'), models.CheckConstraint(condition=models.Q(('last_price__gt', 0)), name='instrument_last_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('avg_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('snapshot_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('risk_level', models.CharField(choices=[('Conservative', 'Conservative'), ('Moderate', 'Moderate'), ('Growth', 'Growth'), ('Aggressive', 'Aggressive')], max_length=12)),
                ('assessed_at', models.DateField()),
                ('horizon_years', models.PositiveSmallIntegerField()),
                ('liquidity_need', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_profiles', to='portfolio.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('FEE', 'Fee')], max_length=8)),
                ('trade_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('SETTLED', 'Settled'), ('PENDING', 'Pending'), ('REVERSED', 'Reversed')], max_length=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.account')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='imports.importbatch')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.instrument')),
            ],
            options={
                'ordering': ['-trade_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ['BROKERAGE', 'MUTUAL_FUND', 'RETIREMENT'])), name='account_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'DORMANT', 'CLOSED'])), name='account_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('goal_type__in', ['RETIREMENT', 'EDUCATION', 'HOME_PURCHASE', 'EMERGENCY_FUND', 'WEALTH_CREATION', 'TRAVEL'])), name='goal_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'MEDIUM', 'HIGH'])), name='goal_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='goal_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('current_funded_amount__gte', 0)), name='goal_funded_non_negative'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['snapshot_date'], name='holding_snapshot_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('account', 'instrument', 'snapshot_date'), name='holding_unique_position_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='holding_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('avg_cost__gte', 0)), name='holding_avg_cost_non_negative'),
        ),
        migrations.AddIndex(
            model_name='riskprofile',
            index=models.Index(fields=['customer', '-assessed_at'], name='risk_customer_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskprofile',
            constraint=models.UniqueConstraint(fields=('customer', 'assessed_at'), name='risk_profile_unique_per_day'),
        ),
        migrations.AddConstraint(
            model_name='riskprofile',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__lte', 100)), name='risk_score_max_100'),
        ),
        migrations.AddConstraint(
            model_name='riskprofile',
            constraint=models.CheckConstraint(condition=models.Q(('risk_level__in', ['Conservative', 'Moderate', 'Growth', 'Aggressive'])), name='risk_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='riskprofile',
            constraint=models.CheckConstraint(condition=models.Q(('liquidity_need__in', ['LOW', 'MEDIUM', 'HIGH'])), name='risk_liquidity_valid'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-trade_date'], name='txn_account_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trade_date'], name='txn_trade_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('transaction_type__in', ['BUY', 'SELL', 'DIVIDEND', 'FEE'])), name='txn_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SETTLED', 'PENDING', 'REVERSED'])), name='txn_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='txn_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('transaction_type__in', ['BUY', 'SELL']), ('quantity__gt', 0), ('price__gt', 0)), models.Q(('transaction_type__in', ['DIVIDEND', 'FEE']), ('quantity', 0), ('price', 0)), _connector='OR'), name='txn_quantity_price_match_type'),
        ),
    ]
