# Generated by Django 6.1.1 on 2026-10-05 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='riskprofile',
            name='risk_customer_latest_idx',
        ),
        migrations.AlterField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='customer',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='risk_profiles', to='portfolio.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.account'),
        ),
    ]
