# Generated by Django 6.1.1 on 2026-10-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_reporting_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(max_length=40)),
                ('entity', models.CharField(max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=10, null=True)),
                ('detail', models.TextField()),
            ],
            options={
                'db_table': 'portfolio_reconciliation_exception',
                'ordering': ['exception_type', 'entity_id'],
                'managed': False,
            },
        ),
    ]
